name: flutter_animated_drawings
description: "Animaka — bring your hand-drawn characters to life."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.6.4
  image: ^4.2.0
  vector_math: ^2.1.4
  yaml: ^3.1.2
  file_picker: ^10.3.1
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/sample.png
    - assets/models/drawn_humanoid_pose.onnx
    - assets/bvh/cmu1/
    - assets/bvh/fair1/
    - assets/bvh/rokoko/
    - assets/config/motion/
    - assets/config/retarget/
